package me.mazupy.kairyou.utils;

import static org.lwjgl.glfw.GLFW.*;

public class HumanReadable {
    
    public static String keyCode(int keyCode) {
        if (keyCode >= GLFW_MOUSE_BUTTON_1 && keyCode <= GLFW_MOUSE_BUTTON_LAST) return "M" + (keyCode + 1);
        else if (keyCode > 32 && keyCode < 255) return "" + (char) keyCode; // "!" to "■"

        switch(keyCode) {
            default:
            case -1:
                return "INVALID";
            case 32:
                return "SPACE";
            case 256:
                return "ESCAPE";
            case 257:
                return "ENTER";
            case 258:
                return "TAB";
            case 259:
                return "BACKSPACE";
            case 260:
                return "INSERT";
            case 261:
                return "DELETE";
            case 262:
                return "RIGHT";
            case 263:
                return "LEFT";
            case 264:
                return "DOWN";
            case 265:
                return "UP";
            case 266:
                return "PAGE_UP";
            case 267:
                return "PAGE_DOWN";
            case 268:
                return "HOME";
            case 269:
                return "END";
            case 280:
                return "CAPS_LOCK";
            case 281:
                return "SCROLL_LOCK";
            case 282:
                return "NUM_LOCK";
            case 283:
                return "PRINT_SCREEN";
            case 284:
                return "PAUSE";
            case 290:
                return "F1";
            case 291:
                return "F2";
            case 292:
                return "F3";
            case 293:
                return "F4";
            case 294:
                return "F5";
            case 295:
                return "F6";
            case 296:
                return "F7";
            case 297:
                return "F8";
            case 298:
                return "F9";
            case 299:
                return "F10";
            case 300:
                return "F11";
            case 301:
                return "F12";
            case 302:
                return "F13";
            case 303:
                return "F14";
            case 304:
                return "F15";
            case 305:
                return "F16";
            case 306:
                return "F17";
            case 307:
                return "F18";
            case 308:
                return "F19";
            case 309:
                return "F20";
            case 310:
                return "F21";
            case 311:
                return "F22";
            case 312:
                return "F23";
            case 313:
                return "F24";
            case 314:
                return "F25";
            case 320:
                return "NUM_0";
            case 321:
                return "NUM_1";
            case 322:
                return "NUM_2";
            case 323:
                return "NUM_3";
            case 324:
                return "NUM_4";
            case 325:
                return "NUM_5";
            case 326:
                return "NUM_6";
            case 327:
                return "NUM_7";
            case 328:
                return "NUM_8";
            case 329:
                return "NUM_9";
            case 330:
                return "NUM_DECIMAL";
            case 331:
                return "NUM_DIVIDE";
            case 332:
                return "NUM_MULTIPLY";
            case 333:
                return "NUM_SUBTRACT";
            case 334:
                return "NUM_ADD";
            case 335:
                return "NUM_ENTER";
            case 336:
                return "NUM_EQUAL";
            case 340:
                return "LEFT_SHIFT";
            case 341:
                return "LEFT_CONTROL";
            case 342:
                return "LEFT_ALT";
            case 343:
                return "LEFT_SUPER";
            case 344:
                return "RIGHT_SHIFT";
            case 345:
                return "RIGHT_CONTROL";
            case 346:
                return "RIGHT_ALT";
            case 347:
                return "RIGHT_SUPER";
            case 348:
                return "MENU";
        }
    }
}
